import os
import uuid
from datetime import datetime, timedelta, timezone
from supabase import create_client

url = "https://aepvoyytbfbghigajecz.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlcHZveXl0YmZiZ2hpZ2FqZWN6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDY0NDYyMiwiZXhwIjoyMTAwMjIwNjIyfQ.EsKD9tVIH3UvI1KdbMXxmCwC9tC4be7eq4sQ6MwzExY"
sb = create_client(url, key)

now = datetime.now(timezone.utc)
ORG_FOLLOWFLOW = "00000000-0000-0000-0000-000000000001"
ORG_NAME = "FollowFlow Labs"

commitments_data = [
    {
        "title": "Zero-Downtime Migration to Amazon ECS Fargate v1.4",
        "description": "Orchestrate rolling container deployments across us-east-1 with 0 packet drop and health check verification.",
        "owner_username": "kenji_s",
        "owner_name": "Kenji Sato",
        "status": "VERIFIED",
        "visibility": "public",
        "evidence_type": "aws_resource",
        "evidence_url": "arn:aws:ecs:us-east-1:798404182134:service/followflow-production/followflow-service",
        "risk": "low",
        "progress": 100,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now - timedelta(days=2)).isoformat(),
        "created_at": (now - timedelta(days=10)).isoformat(),
        "updated_at": (now - timedelta(days=2)).isoformat(),
    },
    {
        "title": "Cryptographic Ed25519 Commit Signing Pipeline for SOC2",
        "description": "Enforce verified commit signatures across all core microservice repositories and S3 audit buckets.",
        "owner_username": "devon_c",
        "owner_name": "Devon Clarke",
        "status": "VERIFIED",
        "visibility": "public",
        "evidence_type": "github_repo",
        "evidence_url": "https://github.com/followflow/core/commit/89f02c114ad89b",
        "risk": "low",
        "progress": 100,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now - timedelta(days=1)).isoformat(),
        "created_at": (now - timedelta(days=8)).isoformat(),
        "updated_at": (now - timedelta(days=1)).isoformat(),
    },
    {
        "title": "Sub-10ms Redis Multi-Tier Caching & Invalidation Layer",
        "description": "Implement read-through caching for organization hierarchy, teams directory, and member scores.",
        "owner_username": "elena_v",
        "owner_name": "Elena Rostova",
        "status": "VERIFIED",
        "visibility": "public",
        "evidence_type": "github_repo",
        "evidence_url": "https://github.com/followflow/agent/pull/48",
        "risk": "low",
        "progress": 100,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now - timedelta(days=3)).isoformat(),
        "created_at": (now - timedelta(days=12)).isoformat(),
        "updated_at": (now - timedelta(days=3)).isoformat(),
    },
    {
        "title": "Design System 2.0: Linear-Inspired Accessibility & Theme Tokens",
        "description": "Unify card radiuses, border contrasts (#E4E7EC), and high-legibility typographic hierarchies.",
        "owner_username": "chloe_t",
        "owner_name": "Chloe Tanaka",
        "status": "VERIFIED",
        "visibility": "public",
        "evidence_type": "notion_doc",
        "evidence_url": "https://notion.so/followflow/design-system-2-spec",
        "risk": "low",
        "progress": 100,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now - timedelta(days=4)).isoformat(),
        "created_at": (now - timedelta(days=15)).isoformat(),
        "updated_at": (now - timedelta(days=4)).isoformat(),
    },
    {
        "title": "Claude 3.5 Sonnet Ambiguity Decision Boundary Calibration",
        "description": "Train and evaluate 200 high-entropy tool calling traces to benchmark 85% ambiguity cutoff threshold.",
        "owner_username": "fatima_ai",
        "owner_name": "Fatima Al-Mansoor",
        "status": "ACTIVE",
        "visibility": "public",
        "evidence_type": "aws_resource",
        "evidence_url": "s3://followflow-evaluations/bedrock/calibration-v2.json",
        "risk": "medium",
        "progress": 65,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now + timedelta(days=2)).isoformat(),
        "created_at": (now - timedelta(days=3)).isoformat(),
        "updated_at": now.isoformat(),
    },
    {
        "title": "Next.js 15 Standalone Reverse-Proxy Routing for ECS",
        "description": "Eliminate CORS and localhost port binding issues by embedding internal rewrites in Next.js server runtime.",
        "owner_username": "marcus_v",
        "owner_name": "Marcus Vance",
        "status": "VERIFIED",
        "visibility": "public",
        "evidence_type": "github_repo",
        "evidence_url": "https://github.com/followflow/web/pull/104",
        "risk": "low",
        "progress": 100,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now - timedelta(hours=12)).isoformat(),
        "created_at": (now - timedelta(days=2)).isoformat(),
        "updated_at": (now - timedelta(hours=12)).isoformat(),
    },
    {
        "title": "Enterprise Multi-Organization SLA Policy Engine",
        "description": "Support custom fulfillment rates (95%), 24h grace horizons, and automated breach notifications.",
        "owner_username": "ananya_r",
        "owner_name": "Ananya Roy",
        "status": "ACTIVE",
        "visibility": "public",
        "evidence_type": "notion_doc",
        "evidence_url": "https://notion.so/followflow/enterprise-sla-contracts",
        "risk": "low",
        "progress": 80,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now + timedelta(days=3)).isoformat(),
        "created_at": (now - timedelta(days=4)).isoformat(),
        "updated_at": now.isoformat(),
    },
    {
        "title": "PostgreSQL Connection Pooling & Indexing Audit",
        "description": "Optimize query execution plans on commitments and users tables to maintain <5ms p99 query latency.",
        "owner_username": "david_b",
        "owner_name": "David Becker",
        "status": "VERIFIED",
        "visibility": "public",
        "evidence_type": "aws_resource",
        "evidence_url": "arn:aws:rds:us-east-1:798404182134:db:followflow-pg",
        "risk": "low",
        "progress": 100,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now - timedelta(days=5)).isoformat(),
        "created_at": (now - timedelta(days=14)).isoformat(),
        "updated_at": (now - timedelta(days=5)).isoformat(),
    },
    {
        "title": "Comprehensive E2E Playwright Chaos Suite for Agent Escalations",
        "description": "Simulate 50 parallel unfulfilled commitments and verify that human-in-the-loop approvals fire accurately.",
        "owner_username": "liam_g",
        "owner_name": "Liam Gallagher",
        "status": "ACTIVE",
        "visibility": "public",
        "evidence_type": "github_repo",
        "evidence_url": "https://github.com/followflow/tests/actions/runs/98412",
        "risk": "medium",
        "progress": 70,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now + timedelta(days=1)).isoformat(),
        "created_at": (now - timedelta(days=2)).isoformat(),
        "updated_at": now.isoformat(),
    },
    {
        "title": "Zero-Alarm CloudWatch Synthetics Across All Production APIs",
        "description": "Deploy automated heartbeat probes every 60 seconds against /ping, /health, and /api/commitments.",
        "owner_username": "kofi_m",
        "owner_name": "Kofi Mensah",
        "status": "VERIFIED",
        "visibility": "public",
        "evidence_type": "aws_resource",
        "evidence_url": "arn:aws:cloudwatch:us-east-1:798404182134:alarm:followflow-latency",
        "risk": "low",
        "progress": 100,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now - timedelta(days=1)).isoformat(),
        "created_at": (now - timedelta(days=6)).isoformat(),
        "updated_at": (now - timedelta(days=1)).isoformat(),
    },
    {
        "title": "Strands Agents SDK Loop Idempotency & Replay Protection",
        "description": "Implement transaction deduplication tokens so scheduled follow-ups never send duplicate notifications.",
        "owner_username": "maya_l",
        "owner_name": "Maya Lin",
        "status": "ACTIVE",
        "visibility": "public",
        "evidence_type": "github_repo",
        "evidence_url": "https://github.com/followflow/agent/pull/56",
        "risk": "low",
        "progress": 90,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now + timedelta(hours=18)).isoformat(),
        "created_at": (now - timedelta(days=1)).isoformat(),
        "updated_at": now.isoformat(),
    },
    {
        "title": "AWS Marketplace SaaS Subscription & Metering Connector",
        "description": "Wire hourly active-seat metering and Bedrock token usage tracking into AWS Marketplace billing API.",
        "owner_username": "sofia_r",
        "owner_name": "Sofia Rossi",
        "status": "ACTIVE",
        "visibility": "public",
        "evidence_type": "aws_resource",
        "evidence_url": "arn:aws:aws-marketplace:us-east-1:798404182134:product/followflow-ent",
        "risk": "medium",
        "progress": 55,
        "organization_id": ORG_FOLLOWFLOW,
        "organization_name": ORG_NAME,
        "deadline": (now + timedelta(days=4)).isoformat(),
        "created_at": (now - timedelta(days=5)).isoformat(),
        "updated_at": now.isoformat(),
    },
]

def seed_commitments():
    print("Checking existing commitments...")
    existing = sb.table("commitments").select("title").execute().data or []
    existing_titles = {c["title"] for c in existing}
    
    inserted = 0
    for c in commitments_data:
        if c["title"] not in existing_titles:
            c["id"] = str(uuid.uuid4())
            sb.table("commitments").insert(c).execute()
            inserted += 1
            
    total = len(sb.table("commitments").select("id").execute().data or [])
    print(f"Commitment seeding complete! Added {inserted} new commitments. Total now: {total}")

if __name__ == "__main__":
    seed_commitments()
